steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east5-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA",
        ".",
      ]

  # 2. Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east5-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA",
      ]

  # 3. Deploy container to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "propflow-app"
      - "--image"
      - "us-east5-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA"
      - "--region"
      - "us-east5"
      - "--allow-unauthenticated" # Allow public access (remove if internal only)
      - "--memory"
      - "512Mi"
      - "--platform"
      - "managed"
      - "--set-env-vars"
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "--add-cloudsql-instances"
      - "$PROJECT_ID:us-east5:propflow-db-east"

images:
  - "us-east5-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
