steps:
  # Step 1: Artifact Registry Self-Healing
  - name: "gcr.io/cloud-builders/gcloud"
    id: "setup-artifact-registry"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "🔍 Checking Artifact Registry..."
        gcloud artifacts repositories describe propflow-repo \
          --location=us-east4 \
          --project=${PROJECT_ID} || \
        (echo "📦 Creating Artifact Registry repository..." && \
        gcloud artifacts repositories create propflow-repo \
          --repository-format=docker \
          --location=us-east4 \
          --description="PropFlow Docker repository" \
          --project=${PROJECT_ID})
    timeout: 300s

  # Step 2: Build Docker Image with Complete Environment
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - "build"
      - "--cache-from"
      - "us-east4-docker.pkg.dev/${PROJECT_ID}/propflow-repo/propflow-app:latest"
      - "--build-arg"
      - "NEXT_PUBLIC_GCP_PROJECT_ID=${_PROJECT_ID}"
      - "--build-arg"
      - "GCP_REGION=${_REGION}"
      - "--build-arg"
      - "NEXT_PUBLIC_GCP_REGION=${_REGION}"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_URL=${_APP_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "-t"
      - "us-east4-docker.pkg.dev/${PROJECT_ID}/propflow-repo/propflow-app:latest"
      - "-t"
      - "us-east4-docker.pkg.dev/${PROJECT_ID}/propflow-repo/propflow-app:${SHORT_SHA}"
      - "."
    timeout: 1200s

  # Step 3: Push Docker Image
  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      - "push"
      - "--all-tags"
      - "us-east4-docker.pkg.dev/${PROJECT_ID}/propflow-repo/propflow-app"
    timeout: 600s

  # Step 4: Deploy to Cloud Run with Full Configuration
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-cloud-run"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "propflow-app"
      - "--image"
      - "us-east4-docker.pkg.dev/${PROJECT_ID}/propflow-repo/propflow-app:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--concurrency"
      - "80"
      - "--timeout"
      - "300"
      - "--set-env-vars"
      - "NEXT_PUBLIC_GCP_PROJECT_ID=${_PROJECT_ID},GCP_REGION=${_REGION},NEXT_PUBLIC_GCP_REGION=${_REGION},NEXT_PUBLIC_APP_URL=${_APP_URL},NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY},NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN},NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID},NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "--project"
      - "${PROJECT_ID}"
    timeout: 600s

substitutions:
  _REGION: us-east4
  _PROJECT_ID: propflow-ai-483621
  _APP_URL: https://propflow-ai-483621.web.app
  # Firebase substitutions - these should be set in Cloud Build trigger settings
  _FIREBASE_API_KEY: "" # Set in trigger
  _FIREBASE_AUTH_DOMAIN: "" # Set in trigger
  _FIREBASE_PROJECT_ID: "" # Set in trigger
  _FIREBASE_STORAGE_BUCKET: "" # Set in trigger
  _FIREBASE_MESSAGING_SENDER_ID: "" # Set in trigger
  _FIREBASE_APP_ID: "" # Set in trigger

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  substitutionOption: ALLOW_LOOSE

timeout: 3600s

images:
  - "us-east4-docker.pkg.dev/${PROJECT_ID}/propflow-repo/propflow-app:latest"
  - "us-east4-docker.pkg.dev/${PROJECT_ID}/propflow-repo/propflow-app:${SHORT_SHA}"
