steps:
  # 0. Ensure Artifact Registry exists (Self-Healing)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud artifacts repositories create cloud-run-source-deploy --location=us-east4 --description='Docker repository for Cloud Run' --repository-format=docker --project=$PROJECT_ID || echo 'Repository likely exists or permission denied'",
      ]

  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA",
        "--build-arg",
        "NEXT_PUBLIC_GCP_PROJECT_ID=$PROJECT_ID",
        "--build-arg",
        "GCP_REGION=us-east4",
        "WebContent",
        ".",
      ]

  # 2. Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA",
      ]

  # 3. Deploy container to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ssrpropflowai483621"
      - "--image"
      - "us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA"
      - "--region"
      - "us-east4"
      - "--allow-unauthenticated" # Allow public access (remove if internal only)
      - "--memory"
      - "512Mi"
      - "--platform"
      - "managed"
      - "--set-env-vars"
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "--add-cloudsql-instances"
      - "$PROJECT_ID:us-east4:propflow-db-east"

images:
  - "us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/propflow-app:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
